const path = require("path");

const TEMPLATE_REGISTRY = {
  "basic-js": {
    latest: "1.2.0",
    versions: {
      "1.0.0": {
        files: {
          "output.js": `// Basic JavaScript Template
console.log('Hello from basic-js template!');

module.exports = {
  greet: function() {
    return 'Hello World!';
  }
};
`,
        },
      },
      "1.1.0": {
        files: {
          "output.js": `// Basic JavaScript Template v1.1
// Added: error handling and async support

function greet(name = "World") {
  return \`Hello, \${name}!\`;
}

async function fetchData(url) {
  const response = await fetch(url);
  return response.json();
}

module.exports = { greet, fetchData };
`,
          "utils.js": `// Utility functions

function formatDate(date) {
  return new Date(date).toLocaleDateString();
}

module.exports = { formatDate };
`,
        },
        changelog: "- 新增 utils.js 工具函数文件\n- output.js 支持异步操作",
      },
      "1.2.0": {
        files: {
          "output.js": `// Basic JavaScript Template v1.2
// Added: TypeScript-style JSDoc + error boundaries

/**
 * Greets a person by name
 * @param {string} name - The name to greet
 * @returns {string} Greeting message
 */
function greet(name = "World") {
  if (typeof name !== "string") {
    throw new TypeError("name must be a string");
  }
  return \`Hello, \${name}!\`;
}

/**
 * Fetches JSON data from a URL
 * @param {string} url - The URL to fetch from
 * @param {object} options - Fetch options
 * @returns {Promise<object>} Parsed JSON response
 */
async function fetchData(url, options = {}) {
  if (!url) throw new Error("URL is required");
  const response = await fetch(url, options);
  if (!response.ok) {
    throw new Error(\`HTTP \${response.status}: \${response.statusText}\`);
  }
  return response.json();
}

module.exports = { greet, fetchData };
`,
          "utils.js": `// Utility functions v1.2
// Added: deepClone, debounce

function formatDate(date) {
  return new Date(date).toLocaleDateString();
}

function deepClone(obj) {
  return JSON.parse(JSON.stringify(obj));
}

function debounce(fn, delay = 300) {
  let timer;
  return (...args) => {
    clearTimeout(timer);
    timer = setTimeout(() => fn(...args), delay);
  };
}

module.exports = { formatDate, deepClone, debounce };
`,
          ".eslintrc.cjs": `module.exports = {
  env: {
    es2021: true,
    node: true,
  },
  extends: "eslint:recommended",
  parserOptions: {
    ecmaVersion: "latest",
  },
};
`,
        },
        changelog:
          "- output.js 增加 JSDoc 注释和参数校验\n- utils.js 新增 deepClone、debounce 方法\n- 新增 .eslintrc.cjs 配置文件",
      },
    },
  },
  "node-module": {
    latest: "1.1.0",
    versions: {
      "1.0.0": {
        files: {
          "output.js": `// Node.js Module Template
const path = require('path');

class MyModule {
  constructor() {
    this.name = 'node-module';
  }
  
  getName() {
    return this.name;
  }
}

module.exports = MyModule;
`,
        },
      },
      "1.1.0": {
        files: {
          "output.js": `// Node.js Module Template v1.1
// Added: EventEmitter support + static methods

const { EventEmitter } = require("events");

class MyModule extends EventEmitter {
  static DEFAULT_NAME = "node-module";
  #privateValue;

  constructor(options = {}) {
    super();
    this.name = options.name || MyModule.DEFAULT_NAME;
    this.#privateValue = 0;
  }

  getName() {
    return this.name;
  }

  increment() {
    this.#privateValue++;
    this.emit("change", this.#privateValue);
    return this.#privateValue;
  }
}

module.exports = MyModule;
`,
          "README.md": `# My Node Module

## Usage

\`\`\`js
const MyModule = require("./output");

const mod = new MyModule({ name: "test" });
mod.on("change", (val) => console.log(\`Changed to \${val}\`));
mod.increment();
\`\`\`
`,
        },
        changelog:
          "- 类继承 EventEmitter，支持事件监听\n- 新增私有字段和静态属性\n- 新增 README.md 使用文档",
      },
    },
  },
  "cli-tool": {
    latest: "1.1.0",
    versions: {
      "1.0.0": {
        files: {
          "output.js": `#!/usr/bin/env node
// CLI Tool Template
const chalk = require('chalk');

console.log(chalk.green('🚀 CLI Tool Started!'));
console.log(chalk.blue('Template type: cli-tool'));

// Add your CLI logic here
`,
        },
      },
      "1.1.0": {
        files: {
          "output.js": `#!/usr/bin/env node
// CLI Tool Template v1.1
// Added: commander integration + error handling

const { Command } = require("commander");
const chalk = require("chalk");

const program = new Command();

program
  .name("my-cli")
  .description("A CLI tool generated by learn-cli")
  .version("1.0.0")
  .option("-d, --debug", "enable debug mode")
  .action((options) => {
    if (options.debug) {
      console.log(chalk.gray("[DEBUG] Running in debug mode"));
    }
    console.log(chalk.green("🚀 CLI Tool Started!"));
  });

program.parse();
`,
        },
        changelog: "- 集成 commander.js 命令行框架\n- 支持 --version 和 --debug 选项",
      },
    },
  },
};

function getTemplateInfo(templateName) {
  return TEMPLATE_REGISTRY[templateName] || null;
}

function getLatestVersion(templateName) {
  const info = getTemplateInfo(templateName);
  return info ? info.latest : null;
}

function getTemplateFiles(templateName, version) {
  const info = getTemplateInfo(templateName);
  if (!info || !info.versions[version]) return null;
  return info.versions[version];
}

function getAllVersions(templateName) {
  const info = getTemplateInfo(templateName);
  return info ? Object.keys(info.versions).sort(compareVersions) : [];
}

function compareVersions(v1, v2) {
  const parts1 = v1.split(".").map(Number);
  const parts2 = v2.split(".").map(Number);
  for (let i = 0; i < Math.max(parts1.length, parts2.length); i++) {
    const p1 = parts1[i] || 0;
    const p2 = parts2[i] || 0;
    if (p1 > p2) return 1;
    if (p1 < p2) return -1;
  }
  return 0;
}

function getChangelog(templateName, fromVersion, toVersion) {
  const info = getTemplateInfo(templateName);
  if (!info) return "";
  const allVersions = getAllVersions(templateName);
  const logs = [];
  for (const v of allVersions) {
    if (compareVersions(v, fromVersion) > 0 && compareVersions(v, toVersion) <= 0) {
      const entry = info.versions[v];
      if (entry.changelog) {
        logs.push(`**v${v}**:\n${entry.changelog}`);
      }
    }
  }
  return logs.length > 0 ? logs.join("\n\n") : "无变更记录";
}

module.exports = {
  TEMPLATE_REGISTRY,
  getTemplateInfo,
  getLatestVersion,
  getTemplateFiles,
  getAllVersions,
  compareVersions,
  getChangelog,
};
